/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package softwareengineering_ae2;

import softwareengineering_ae2.PersonClasses.Administrator;
import softwareengineering_ae2.PersonClasses.Director;

import java.io.IOException;
import java.util.Scanner;


public class App {
    public static void main(String[] args) throws IOException {
        Scanner r = new Scanner(System.in);
        System.out.println("are you a Class Director or Administrator");
        var ans =  r.nextLine();
        if(ans.equals("admin")){
            Administrator admin = new Administrator();
            admin.run();
        }
        if(ans.equals("director")){
            Director director = new Director("",0,0,"");
            director.addRequirments();
        }
    }
}
