/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package softwareengineering_ae2;

import com.fasterxml.jackson.core.JsonProcessingException;
import softwareengineering_ae2.datastore.DataStore;

import java.io.IOException;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

    }
}
